spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: METRO_APP
    password: 9251

    hikari:
      maximum-pool-size: 20

  liquibase:
#    database-change-log-table: schema_history
    change-log: classpath:/db/changelog-master.xml
    enabled: true


  jpa:
    show-sql: true

  kafka:
    bootstrap-servers:
      - localhost:29092

  freemarker:
    charset: UTF-8
    template-loader-path:
      - classpath:/templates
    suffix: html
    settings:
      locale: pt_BR







